// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCCoreEFDBFIrstApp.Models.Entities;

public partial class TblProduct
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public decimal UnitPrice { get; set; }

    public string Description { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }
}